export const ADD_BUN: "ADD_BUN" = "ADD_BUN";
export const ADD_FILLING: "ADD_FILLING" = "ADD_FILLING";
export const DELETE_FILLING: "DELETE_FILLING" = "DELETE_FILLING";
export const MOVE_ITEM: "MOVE_ITEM" = "MOVE_ITEM";
export const RESET_CONSTRUCTOR: "RESET_CONSTRUCTOR" = "RESET_CONSTRUCTOR";
export const GENERATE_ID: "GENERATE_ID" = "GENERATE_ID";
